In [1]:
##Control Flow Assignment Questions

In [1]:
#Q1. Write a Python program that checks if a given number is positive, negative, or zero.


n=int(input("Enter number: "))
if(n>0):
    print("Number is positive")
else:
    print("Number is negative")

Enter number:  -77


Number is negative


1. User must first enter the value and store it in a variable.

2. Use an if statement to make a decision.

3. If the value of the number is greater than 0, “Number is positive” is printed.

4. If the value of the number if lesser than 0, ”Number is negative” is negative.

In [1]:
#Q2. Create a program to determine if a person is eligible to vote based on their age


age = int(input("Enter age : "))


if age >= 18:
    print("Eligible for Voting!")
else:
    print("Not Eligible for Voting!")

Enter age :  31


Eligible for Voting!


1. User must first enter the value and store it in a variable.

2. Use an if statement to make a decision.

3. If the value of the number is greater than 18, Eligible for Voting.

4. If the value of the number if lesser than 18, Not Eligible for Voting!.

In [4]:
#Q3. Write a program to find the maximum of two given numbers using conditional statements.


a=int(input("Enter a number: "))
b=int(input("Enter a number: "))
if a>b:
    print(a,' is a maximum number')
else:
    print(b,'is a maximum number')

Enter a number:  77
Enter a number:  88


88 is a maximum number


This program will get the two inputs from the user to get a maximum element from the given inputs. 

In an, if statement we are giving a condition like if a>b, print this statement.

If not, print the else statement. So it will take the input and print the result after checking with a given condition.

In [8]:
#Q4. Develop a program that calculates the grade of a student based on their exam score.


score = float(input("Enter your exam score: "))
exam_score=score/5


if exam_score >= 90:
    grade = "A"
elif exam_score >= 80:
    grade = "B"
elif exam_score >= 70:
    grade = "C"
elif exam_score >= 60:
    grade = "D"
else:
    grade = "F"

# Print the student's grade.
print("Your grade is", grade)

Enter your exam score:  234


Your grade is F


This program first gets the student's exam score from the user and calculate the percentage . Then, it calculates the student's grade based on the following grading scale:
    
              90-100: A
              
              80-89: B
              
              70-79: C
              
              60-69: D
            
              Below 60: F

Finally, the program prints the student's grade to the console.

Here is an example of how the program would work:

In [9]:
#Q5. Create a program that checks if a year is a leap year or not

year=int(input("Enter year to be checked:"))
if(year%4==0 and year%100!=0 or year%400==0):
    print("The year is a leap year!")
else:
    print("The year isn't a leap year!")

Enter year to be checked: 1605


The year isn't a leap year!


1. User must first enter the year to be checked.

2. The if statement checks if the year is a multiple of 4 but isn’t a multiple of 100 or if it is a multiple of 400 (not every year that is a multiple of 4 is a leap year).

3. If the statment is true then leap year else not a leap year.Then the result is printed.

In [10]:
#Q6. Write a program to classify a triangle based on its sides' lengths

y=int(input("Enter the first side length :"))
z=int(input("Enter the second side length :"))
x=int(input("Enter the Third side length  :"))
if x==y and y==z:
    print(":: Equilateral ::")
elif x==y or y==z or x==z:
    print(":: Isosceles ::")
else:
    print(":: Scalene ::")

Enter the first side length : 6
Enter the second side length : 7
Enter the Third side length  : 8


:: Scalene ::


We will define a function and implement the following with the help of conditional statement:

                        if all three sides are equal then it will be printed as An equilateral triangle

                        else  at least two equal sides will be printed as An isosceles triangle
                        
                        else A scalene triangle
                    
Now in the the drivers code take 3 variale and take input from the user & call the function.

In [12]:
#Q7. Build a program that determines the largest of three given numbers.

def largest(num1, num2, num3):
    if (num1 > num2) and (num1 > num3):
        largest_num = num1
    elif (num2 > num1) and (num2 > num3):
        largest_num = num2
    else:
        largest_num = num3
    print("The largest of the 3 numbers is : ", largest_num)

          
number1 = int(input('Enter First number : '))
number2 = int(input('Enter Second number : '))
number3 = int(input('Enter Third number : '))

Enter First number :  33
Enter Second number :  33
Enter Third number :  22


Use function largest(num1, num2, num3)

check if num1 is larger than num1 and num2, if true num1 is largest, else

check if num2 is larger than num1 and num3, if true num2 is largest,

if both the above fails, num3 is largest

Print the largest number

In [13]:
#Q8. Develop a program that checks whether a character is a vowel or a consonant.

n=str(input("Enter the character : "))
vowels="AEIOUaeiou"
if n in vowels:
    print(":::: Vowel ::::")
else:
    print(":::: Consonant ::::")

Enter the character :  h


:::: Consonant ::::


1. Take the value of the string character and store in a variable.

2. now Use an if statement to determine whether character is a vowel or a consonant. if true then vowel else constant.

3. Exit.

In [14]:
#Q9. Create a program to calculate the total cost of a shopping cart based on discounts

def check_discount(x):
    if x>0 and x<1000:
        print(":: Discounted Amount ::",x*0.95)
    elif x>1000 and x<3000:
        print(":: Discounted Amount ::",x*0.90)
    elif x>3000 and x<10000:
        print(":: Discounted Amount ::",x*0.85)
    elif x>10000:
        print(":: Discounted Amount ::",x*0.75)
    else:
        print(":: The Price is invalid ::")
        
x=int(input("Enter the total value you want to check discount on  :"))
check_discount(x)

Enter the total value you want to check discount on  : 5500


:: Discounted Amount :: 4675.0


Firstly take a input from user and store in a varible 

Now call the function check_discount with argument x.

In function check the discount  with the help of conditional element.

Now according to the conditional staments print the  discount value according to the purchase amount  .

In [16]:
#Q10. Write a program that checks if a given number is even or odd.

num = int(input("Enter a Number:")) 
if num % 2 == 0: 
  print("Given number is Even") 
else: 
  print("Given number is Odd")

Enter a Number: 98074


Given number is Even


Start

Insert a number.

If the given number is divisible by 2, then print,” Given number is even”.

If the given number is not divisible by 2, then print ,”Given number is odd”.

Stop

In [17]:
#Intermediate Level:

In [18]:
#Q11. Write a program that calculates the roots of a quadratic equation .



print("Equation: ax^2 + bx + c ")
a=int(input("Enter a: "))
b=int(input("Enter b: "))
c=int(input("Enter c: "))
d=b**2-4*a*c
d1=d**0.5
if(d<0):
    print("The roots are imaginary. ")
else:
    r1=(-b+d1)/2*a
    r2=(-b-d1)/2*a
    print("The first root: ",round(r1,2))
    print("The second root: ",round(r2,2))

Equation: ax^2 + bx + c 


Enter a:  3
Enter b:  5
Enter c:  4


The roots are imaginary. 


1. User must enter the coefficients of the equations and store it in three separate variables.

2. The value value of the discriminant, d, is found out which determines the nature of roots of the equation.

3. If the value of the discriminant is lesser than 0, the roots are imaginary.

4. If the value of the discriminant is greater than 0, the roots aren’t imaginary.

5. The value of the roots is found out using the quadratic formula.

6. The roots of the equation are printed.

In [20]:
#Q12. Create a program that determines the day of the week based on the day number (1-7).



day = int(input("Enter a number from 1 to 7: "))

if day == 1:
    print(day, "is Sunday")
elif day == 2:
    print(day, "is Monday")
elif day == 3:
    print(day, "is Tuesday")
elif day == 4:
    print(day, "is Wednesday")
elif day == 5:
    print(day, "is Thursday")
elif day == 6:
    print(day, "is Friday")
elif day == 7:
    print(day, "is Saturday")
else:
    print("Wrong input! Please enter a number from 1 to 7.")

Enter a number from 1 to 7:  4


4 is Wednesday


To implement this, we need to take input from the user and store it in a variable.

After taking input from the user, we have to compare that number with 1 to 7, or we can say, compare that number with a day of the week.

So the logic goes like– if the number is equal to 1, then it is Monday, if the number is 2, then it is Tuesday; like that, we have to compare with each day of the week.


In [26]:
#Q13. Develop a program that calculates the factorial of a given number using recursion


def fact_rec(n):
    if n==1:
        return n
    else:
        return n*fact_rec(n-1)
            
        
        
n=int(input("Enter the number : "))
fact_rec(n)

Enter the number :  5


120

Firstly Create a function fact_rec with argument n with base condition n==1.

Now with the help of else statement call the recursively to determine the variable.

In the drivers code take variable for user input and call then function.

In [27]:
#Q14. Write a program to find the largest among three numbers without using the `max()` function


def greater_3(x,y,z):
    if x > y and x>z:
        print(":: x is the greatest ::")
    elif y>x and y>z:
         print(":: y is the greatest ::")
    elif z>x and z>y:
         print(":: z is the greatest ::")
    elif x==y or y==z or x==z:
        if x==y and y>z:
            print(":: x & y is the greatest ::")
        elif x==z and y<z:
            print(":: x & z is the greatest ::")
        else:
            print(":: z & y is the greatest ::")
    else:
        print(":: All are equal ::")
        
        
x=int(input("Enter the first number  :"))
y=int(input("Enter the second number  :"))
z=int(input("Enter the third number:"))
greater_3(x,y,z)

Enter the first number  : 33
Enter the second number  : 22
Enter the third number: 33


:: x & z is the greatest ::


In this method, we manually compare each of the numbers from the other numbers to find the maximum or the largest among them.

We will define a function and implement the following with the help of conditional statement:
        
                            if n1 is greater than both n2 and n3 then it will be printed as largest

                            else if n2 is greater than both n1 and n3 then n2 will be printed as largest

                            else n3 is greater than both n1 and n2 then n3 will be printed as largest
                            
                            else if x is equal to y & both are greater than z then print them as largest or y is equal to z & 
                            both are greater than x then print them as largest or x is equal to z & both are greater than y 
                            then print them as largest
                            
                            else all are equal

Now in the the drivers code take 3 variable and take input from the user & call the function.

In [32]:
#Q15. Create a program that simulates a basic ATM transaction menu.

import random

print("1. Check balance")
print("2. Withdraw")
print("3. Deposit")
print("4. Exit")

choice = input("Enter your choice: ")
random_integer = random.randint(1000, 100000)


if choice == "1":
    print("Your account balance is : ",random_integer)
elif choice == "2":
    amount = int(input("Enter the amount to withdraw: "))
    print(amount,"Amount debited from your account . Please collect your cash ")
elif choice == "3":
    amount = int(input("Enter the amount to deposit: "))
    print(amount,"Amount credited from your account . Please submitted your cash ")
elif choice == "4":
    print("Thankyou for choosing banking with us ")
else:
    print("Invalid choice")

1. Check balance
2. Withdraw
3. Deposit
4. Exit


Enter your choice:  1


Your account balance is :  80742


Firstly import random function and print the options 

After that take choice from user and a random integer with a limit of 1000 to 100000

Now with the help of if else & random function simulates the basic ATM transactions

Program Ends.

In [33]:
#Q16. Build a program that checks if a given string is a palindrome or not

string=str(input("Enter string:"))
if(string==string[::-1]):
      print("The string is a palindrome")
else:
      print("The string isn't a palindrome")

Enter string: madam


The string is a palindrome


1. Take a string from the user and store it in a variable.

2. Reverse the string using string slicing and compare it back to the original string.

3. Print the final result

4. Exit.

In [4]:
#Q17. Write a program that calculates the average of a list of numbers, excluding the smallest and largest values.

def average(list1):
    avr=sum(list1)/len(list1)
    return avr
def exclude_smallest(list1):
    smallest = min(list1)
    list1.remove(smallest)
    return list1
def exclude_largest(list1):
    largest = min(list1)
    list1.remove(largest)
    return list1

print("Enter the list element and put space between two entries : ")
list1=list(map(int,input().split()))
print("1. Average")
print("2. Exclude Smallest")
print("3. Exclude Largest")
print("4. Exit")

choice = input("Enter your choice: ")


if choice == "1":
    avr=average(list1)
    print("Average of list is : ",avr)
elif choice == "2":
    lst = exclude_smallest
    print(lst,"Amount debited from your account . Please collect your cash ")
elif choice == "3":
    lst1 = exclude_largest(list1)
    print(list(lst1))
elif choice == "4":
    print(":::: Thankyou :::: ")

Enter the list element and put space between two entries : 


 11 22 33 122 44 33


1. Average
2. Exclude Smallest
3. Exclude Largest
4. Exit


Enter your choice:  3


[22, 33, 122, 44, 33]


Firstly take a list of number as user input and print the operations option. 

After that take choice from user and store in a variable.

Now with the help of if else statement calculate the average of a list of numbers, excluding the smallest and largest values

Program Ends.

In [6]:
#Q18. Develop a program that converts a given temperature from Celsius to Fahrenheit.

celsius=int(input("Enter the temperature in celcius:"))
f=(celsius*1.8)+32
print("Temperature in farenheit is:",f)

Enter the temperature in celcius: 36


Temperature in farenheit is: 96.8


1. User must first enter the value of temperature in Celsius.

2. Using the formula of: f=(c*1.8)+32, convert Celsius to Fahrenheit.

3. Print the temperature in Fahrenheit.

In [9]:
#Q19. Create a program that simulates a basic calculator for addition, subtraction, multiplication, and division

def add(a,b):
    return a+b

def sub(a,b):
    return a-b

def mul(a,b):
    return a*b

def div(a,b):
    return a/b

a=int(input("Enter first number: "))
b=int (input("Enter second number: "))
print("0. Exit")
print("1. Add")
print("2. Subtraction")
print("3. Multiplication")
print("4. Division")
choice=int(input("Enter choice: "))
if choice==1:
    print("Result: ",add(a,b))
elif choice==2:
    print("Result: ",sub(a,b))
elif choice==3:
    print("Result: ",mul(a,b))
elif choice==4:
    print("Result: ",div(a,b))
elif choice==0:
    print(":::: Thakyou ::::")
else:
    print("Invalid choice!!")
 

Enter first number:  66
Enter second number:  11


0. Exit
1. Add
2. Subtraction
3. Multiplication
4. Division


Enter choice:  3


Result:  726


Firstly Methods for adding, substracting, multiplying, dividing two numbers and returning their respective results should be defined.

Then the menu is printed and the choice is taken from the user.

Using the if -else, the respective functions  is called according to the choice taken from the user.

When the choice is 0, the loop is exited.

The final result is printed.



In [4]:
#20. Write a program that determines the roots of a cubic equation using the Cardano formula.


def diff(n, mid):
    if (n > (mid * mid * mid)):
        return (n - (mid * mid * mid))
    else:
        return ((mid * mid * mid) - n)

def cubicRoot(n):

    start = 0
    end = n

    e = 0.0000001
    while (True):
 
        mid = (start + end) / 2
        error = diff(n, mid)

        if (error <= e):
            return mid

        if ((mid * mid * mid) > n):
            end = mid
        else:
            start = mid

            
n = int(input("Enter the number : "))
print("Cubic root of", n, "is",
      round(cubicRoot(n), 6))

Enter the number :  512


Cubic root of 512 is 8.0


The main steps of our program for calculating the cubic root of a number n are: 

Initialize start = 0 and end = n

Calculate mid = (start + end)/2

Check if the absolute value of (n – mid*mid*mid) < e. If this condition holds true then mid is our answer so return mid. 

If (mid*mid*mid)>n then set end=mid

If (mid*mid*mid)<n then set start=mid

In [ ]:
#Advanced Level

In [2]:
#21. Create a program that calculates the income tax based on the user's income and tax brackets



income=int(input("Please enter your annual package : "))
if income <= 250000:  #2 Lakh 50 thousand
    tax = 0

elif income <= 500000: #5 Lakh
    tax = (income - 250000) * 0.05

elif income <= 750000: #7 lakh 50 thousand
    tax = (income - 500000) * 0.10 + 12500 

elif income <= 1000000: #10 Lakh
    tax = (income - 750000) * 0.15 + 37500 

elif income <= 1250000: #12 lakh 50 thousand
    tax = (income - 1000000) * 0.20 + 75000 

elif income <= 1500000: #15 lakh
    tax = (income - 1250000) * 0.25 + 125000 

else:
    tax = (income - 1500000) * 0.30 + 187500

print("you owe", tax, "Rupees in tax!")

Please enter your annual package :  1600000


you owe 217500.0 Rupees in tax!


Take a per annum income from the user as input and store it in a variable.

Now we will put if and else statements here to full fill our income tax calculating conditions as given below:

                    If income is less than or equals to Rs. 2,50,000 then tax will be zero.
                    
                    If income is less than or equals to Rs. 5,00,000 then tax will be 5% of total income exceeding 
                    Rs. 2,50,000
                    
                    If income is less than or equals to Rs. 7,50,000 then tax will be 10% of total income exceeding 
                    Rs. 5,00,000 with an additional cost of Rs. 12,500.
                    
                    If income is less than or equals to Rs. 10,00,000 then tax will be 15% of total income exceeding 
                    Rs. 7,50,000 with an additional cost of Rs. 37,500.
                    
                    If income is less than or equals to Rs. 12,50,000 then tax will be 20% of total income exceeding 
                    Rs. 10,00,000 with an additional cost of Rs. 75,000.
                    
                    If income is less than or equals to Rs. 15,00,000 then tax will be 25% of total income exceeding 
                    Rs. 12,50,000 with an additional cost of Rs. 1,25,000.
                    
                    If income is more than Rs. 15,00,000 then tax will be 30% of total income exceeding Rs. 15,00,000 
                    with an additional cost of Rs. 1,87,500.

In [4]:
#Q22. Write a program that simulates a rock-paper-scissors game against the computer




import random

actions = ['rock', 'paper', 'scissors']

user_choice = input('Enter your choice (rock, paper or scissors): ')

program_choice = random.choice(actions)

print(f"Your choice {user_choice}, computer choice {program_choice}\n")

if user_choice == program_choice:
    print(f"Both players selected {user_choice}. It's a tie!")
elif user_choice == "rock":
    if program_choice == "scissors":
        print("You win! because Rock smashes scissors.")
    else:
        print("You lose :( Paper covers rock!")
elif user_choice == "paper":
    if program_choice == "rock":
        print("You win! because Paper covers rock.")
    else:
        print("You lose :( Scissors cuts paper!")
elif user_choice == "scissors":
    if program_choice == "paper":
        print("You win! because Scissors cuts paper.")
    else:
        print("You lose :( Rock smashes scissors!")


Enter your choice (rock, paper or scissors):  rock


Your choice rock, computer choice scissors

You win! because Rock smashes scissors.


To build the Rock paper scissors python game, we will divide the problem statement into three simple steps to help us build the game.

The steps are as follows:

                         Take the input from the user to know their choice (rock, paper or scissors).
                         
                         Randomly allow the program to choose its choice.
                         
                         Based on the game rules, decide the winner and display the winner on the screen.

In [10]:
#Q23. Develop a program that generates a random password based on user preferences (length, complexity)




import random
def generatePassword(n):
    characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ123456789!@#$%^&*()"

    password = ""

    for i in range(n):
        password += random.choice(characters)
    return password



n = int(input("Enter the length of the password :"))
password = generatePassword(n)
print("A randomly selected password is:", password)


Enter the length of the password : 14


A randomly selected password is: QLh641I3WcKI9B


Firstly import random and define the valid characters for the password and store it in a variable.

Now with the help of loop and random genrate the password and return

In the drivers code take user input for the length of the password.

Call the function and sotre the return value in a variable .

Print the variable and program end.

In [11]:
#Q24. Create a program that implements a simple text-based adventure game with branching scenarios






import random
def games(words):
    word = random.choice(words)
    print("Guess the characters")
    guesses = ''
    turns = 12
    while turns > 0:
        failed = 0
        for char in word:
            if char in guesses:
                print(char, end=" ")
            else:
                print("_")
                failed += 1
        if failed == 0:
            print("You Win")
            print("The word is: ", word)
            break
        print()
        guess = input("guess a character:")
        guesses += guess
        if guess not in word:
            turns -= 1
            print("Wrong")
            print("You have", + turns, 'more guesses')
            if turns == 0:
                print("You Loose")
 




name = input("What is your name? ")
n=int(input("Enter your choice 1 for easy 2 for medium & 3 for hard :"))
 
print("Good Luck ! ", name)
 
words = ["airplane","boat","baby","ears","scissors","cough","cold","phone","laugh","blink",
         "hairbrush","sneeze","spin","hammer","book","phone","toothbrush","jump","clap","slap"]
words1=["archer","ghost","balance","shoelaces","sick","balloon","banana","monster","hiccup",
        "stomp","hurt","hungry","slip","karate","ladder","scare","fishing","dizzy","read","hot"] 
words2=["birthday","president","apartment","cradle","coffee","trampoline","waterfall","window","proud","stuckup","flashlight","marry",
        "overwhelm","judge","shadow","halo","measure","clown","chomp","slither"]
if n==1:
    games(words)
elif n==2:
    games(words1)
elif n==3:
    games(words2)
else:
    print("Input Invalid ")

What is your name?  Vikas
Enter your choice 1 for easy 2 for medium & 3 for hard : 2


Good Luck !  Vikas
Guess the characters
_
_
_
_
_



guess a character: g


Wrong
You have 11 more guesses
_
_
_
_
_



guess a character: a


Wrong
You have 10 more guesses
_
_
_
_
_



guess a character: e


Wrong
You have 9 more guesses
_
_
_
_
_



guess a character: o


_
_
o _
_



guess a character: t


_
t o _
_



guess a character: m


_
t o m _



guess a character: p


_
t o m p 


guess a character: s


s t o m p You Win
The word is:  stomp


The code starts by asking the user to enter their name & dificulty level.

The code then prints a message saying “Good Luck!”and sets a variable called name to the inputted name.

Next, the code creates a list of words using the built-in function word().

This function takes in an input string and returns a list of strings.

In this case, the list will contain five strings: rainbow, computer, science, programming, and python.

The next part of the code is where the randomness happens.

The code will randomly choose one string from the list of words and store it in word variable.

Then it will print out that word along with a space at the end.

After printing out each word, the code checks to see if any user has entered an incorrect letter by comparing each character in guess with those in word .

If they don’t match up then guess is set to “Wrong” and turns is decreased by 1 .

If there are no more letters left in guess , then Guess You Lose is printed .

Otherwise turn s is increased by 1 and loop continues until either Guess You Win or Wrong is printed .

Finally , if turn s equals 0 , then you have won !

Otherwise Wrong will be

The code will randomly choose one word from a list of words.

The user is then asked to enter the characters for that word.

Once the user enters all of the characters, the code checks to see if those characters are in the word that was chosen.

If they are not, it prints out “Wrong” and decreases the number of turns left for the user by 1.

If all turns have been used, then the code will print “You Lose.”

In [4]:
#Q25. Build a program that solves a linear equation  for x, considering different cases.




def solve(equation): 
    s1 = equation.replace('x', 'j') 
    s2 = s1.replace('=', '-(')
    s = s2+')'
    z = eval(s, {'j': 1j}) 
    real, imag = z.real, -z.imag 
    if imag: 
        return "x = %f" % (real/imag) 
    else: 
        if real: 
            return "No solution"
        else: 
            return "Infinite solutions"
  
  
equation = "2+3x=5x-7"
print(solve(equation)) 

x = 4.500000


Step 1: We will use the replace() in python to replace “=” with “-(” and replace “x” with “j”.


Step 2: The string is then added with “+)” to complete the expression.


Step 3: Then { “j” : 1j} is done to change the equation into a format that can be easily evaluated by the eval() function. In this step all the constant terms are evaluated and the x terms or the imaginary terms as well.


Step 4: Then the evaluated expression is simply broken down into the real and imaginary parts. If the imaginary part exists or the x is true and not zero the answer is printed else if the imaginary part is 0 and the real part is true there is no solution or else there are infinite solutions. Here,

In [2]:
#Q26. Write a program that simulates a basic quiz game with multiple-choice questions and scoring.



print("Wellcome to quiz game !!")
print('NOTE: if your spelling is incorrect then it is considered as wrong answer')
score = 0
question_no = 0
playing = input('Do you want to play ? ').lower()
if playing == 'yes':
    question_no += 1
    ques = input(f'\n{question_no}. what does CPU stand for? ').lower()
    if ques == 'central processing unit':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> central processing unit')

# ------1
    question_no += 1
    ques = input(f'\n{question_no}. what does GPU stand for? ').lower()
    
    if ques == 'graphics processing unit':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> graphics processing unit')

# -----2
    question_no += 1
    ques = input(f'\n{question_no}. what does RAM stand for? ').lower()
    
    if ques == 'random access memory':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> random access memory')

# -----3
    question_no += 1
    ques = input(f'\n{question_no}. what does PSU stand for? ').lower()
    
    if ques == 'power supply unit':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> power supply unit')


# -----4
    question_no += 1
    ques = input(f'\n{question_no}. what does ROM stand for? ').lower()
    
    if ques == 'read only memory':
        score +=1
        print('correct! you got 1 point')
        
    else:
        print('Incorrect!')
        print(f'current answer is --> read only memory')


# ------5 

else:
    print('thankyou you are out of a game.')
    quit()

print(f'\nnumber of question is {question_no}')
print(f'your score is {score}')
try:
    percentage = (score *100)/question_no
except ZeroDivisionError:
    print('0% quetions are correct')

print(f'{percentage}% questions are correct.')



Wellcome to quiz game !!
NOTE: if your spelling is incorrect then it is considered as wrong answer


Do you want to play ?  yes

1. what does CPU stand for?  graphics processing unit


Incorrect!
current answer is --> central processing unit



2. what does GPU stand for?  graphics processing unit


correct! you got 1 point



3. what does RAM stand for?  random access memory


correct! you got 1 point



4. what does PSU stand for?  power supply unit


correct! you got 1 point



5. what does ROM stand for?  read only memory


correct! you got 1 point

number of question is 5
your score is 4
80.0% questions are correct.


Create one variable for counting score e.g score.

Ask questions to a user (using the input() function)

if a user gives a correct answer then increase a score by 1 and print(correct!)

if given answer of a user is incorrect then print(incorrect!)

and at last print score of the user.

In [10]:
#Q27. Develop a program that determines whether a given year is a prime number or not.




def is_prime(year):
    if year <= 1:
        return False
    for i in range(2, int(year**0.5) + 1):
        if year % i == 0:
            return False
    return True




year = int(input("Enter the year : "))

if is_prime(year):
  print(year," is a prime number.")
else:
  print(year," is not a prime number.")

Enter the year :  2203


2203  is a prime number.


This program first checks if the given year is less than or equal to 1. If it is, then the program returns False because 1 is not a prime number.

Otherwise, the program iterates through all the numbers from 2 to the square root of the given year. 

If any of these numbers divide evenly into the given year, then the program returns False because the given year is not prime.

If the program reaches the end of the loop without finding any factors of the given year, then the program returns True because the given year is prime.

In [12]:
#Q28. Create a program that sorts three numbers in ascending order using conditional statements

def sort_three_numbers(a, b, c):
    if a > b:
        a, b = b, a
    if b > c:
        b, c = c, b
    if a > b:
        a, b = b, a
    return [a, b, c]



a=int(input("Enter the first number :"))
b=int(input("Enter the second number :"))
c=int(input("Enter the third number :"))
sort_three_numbers(a, b, c)

Enter the first number : 33
Enter the second number : 22
Enter the third number : 56


[22, 33, 56]

This program works by first comparing the first two numbers and swapping them if necessary. 

Then, it compares the second two numbers and swaps them if necessary.

Finally, it compares the first two numbers again and swaps them if necessary. 

This ensures that the three numbers are in ascending order.

In [13]:
#Q29. Build a program that determines the roots of a quartic equation using numerical methods.


print("Equation: ax^2 + bx + c ")
a=int(input("Enter a: "))
b=int(input("Enter b: "))
c=int(input("Enter c: "))
d=b**2-4*a*c
d1=d**0.5
if(d<0):
    print("The roots are imaginary. ")
else:
    r1=(-b+d1)/2*a
    r2=(-b-d1)/2*a
    print("The first root: ",round(r1,2))
    print("The second root: ",round(r2,2))

Equation: ax^2 + bx + c 


Enter a:  6
Enter b:  10
Enter c:  8


The roots are imaginary. 


1. User must enter the coefficients of the equations and store it in three separate variables.

2. The value value of the discriminant, d, is found out which determines the nature of roots of the equation.

3. If the value of the discriminant is lesser than 0, the roots are imaginary.

4. If the value of the discriminant is greater than 0, the roots aren’t imaginary.

5. The value of the roots is found out using the quadratic formula.

6. The roots of the equation are printed.

In [18]:
#30. Write a program that calculates the BMI (Body Mass Index) and provides health recommendations based on the user's input.


weight = float(input("Enter your weight in kilograms: "))
height = float(input("Enter your height in meters: "))
 
BMI = weight / (height * height)


if BMI < 18.5:
    print("Category: Underweight")
    print(" Eat a variety of foods that give you the nutrition you need.")
elif BMI <= 24.9:
    print("Category: Normal weight")
    print("Keep up the good work and stay maintained")
elif BMI <= 29.9:
    print("Category: Overweight")
    print("Reduce-calorie diet and exercise regularly.")
elif BMI <= 34.9:
    print("Category: Severely Overweight")
elif BMI <= 39.9:
    print("Category: Obesity")
    print("Reduce the number of calories consumed from fats and sugars, increasing the portion of daily intake of fruit, vegetables, legumes, whole grains and nuts, and engaging in regular physical activity")
else:
    print("Category: Severely Obesity")
    print("Reduce the number of calories consumed from fats and sugars, increasing the portion of daily intake of fruit, vegetables, legumes, whole grains and nuts, and engaging in regular physical activity")


Enter your weight in kilograms:  85
Enter your height in meters:  1.82


Category: Overweight
Reduce-calorie diet and exercise regularly.


Define 2 variable & Prompt the user to enter their weight and height

Now Calculate the BMI with the help of the formula BMI = weight / (height * height)

Now Classify the BMI by executing the following with the help of the if-else statement

            if BMI is less than or equal to 18.4 then You are underweight. will be printed.
    
            if BMI is less than or equal to 24.9 then You are healthy. will be printed.
        
            if BMI is less than or equal to 29.9 then You are over weight. will be printed.
            
            if BMI is less than or equal to 34.9 then You are severely over weight. will be printed.
            
            if BMI is less than or equal to 39.9 then You are obese. will be printed.
            
            if BMI none of the above are true then You are severely obese. will be printed.

In [1]:
#Challenge Level:

In [3]:
#Q31. Create a program that validates a password based on complexity rules (length, characters, etc.).




def validate_password(password):
  if len(password) < 8:
    return False
  if not any(char.isupper() for char in password):
    return False
  if not any(char.islower() for char in password):
    return False
  if not any(char.isdigit() for char in password):
    return False
  if not any(char in "!@#$%^&*()" for char in password):
    return False
  return True



password = input("Enter your password: ")
if validate_password(password):
  print("Your password is valid.")
else:
  print("Your password is invalid.")

Enter your password:  Password@1234


Your password is valid.


This program first checks if the password is at least 8 characters long. 

If it is not, the program returns False.

Otherwise, the program checks if the password contains at least one uppercase letter, one lowercase letter, one number, and one special character. 

If the password does not contain all of these elements, the program returns False. Otherwise, the program returns True.

In [6]:
#Q32. Develop a program that performs matrix addition and subtraction based on user input.

import numpy as np


a = int(input("Enter the first dimension of first array "))
b=int(input("Enter the first dimension of first array "))
l=a*b
print("\n")
lst=list(int(num) for num in input("Enter the list items separated by space ").strip().split())[:l]
A=np.array(lst)
A=A.reshape(a,b)
aa = int(input("Enter the first dimension of first array "))
bb=int(input("Enter the first dimension of first array "))
ll=a*b
print("\n")
lst=list(int(num) for num in input("Enter the list items separated by space ").strip().split())[:ll]
B=np.array(lst)
B=B.reshape(aa,bb)
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
print("1.Add")
print("2.Subtract")
print("3.Exit")
choice=int(input("Enter your choice"))
if choice==1:
    print("Addition of two matrix")
    print(np.add(A, B))
elif choice==2:
    print("Subtraction of two matrix")
    print(np.subtract(A, B))
elif choice==3:
    print("---------------Thankyou--------------------")
else:
    print("------------------Invalid Input--------------")

Enter the first dimension of first array  3
Enter the first dimension of first array  3


Enter the list items separated by space  2 3 4 5 6 7 8 9 10
Enter the first dimension of first array  3
Enter the first dimension of first array  3


Enter the list items separated by space  11 22 33 44 55 66 77 88 99 


Printing elements of first matrix
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]
Printing elements of second matrix
[[11 22 33]
 [44 55 66]
 [77 88 99]]
1.Add
2.Subtract
3.Exit


Enter your choice 2


Subtraction of two matrix
[[ -9 -19 -29]
 [-39 -49 -59]
 [-69 -79 -89]]


Firstly import numpy as np and by the help of list , loop and inbuilt function take two arrays as input.

After that with the help of conditional let the user choose the operation

Now after the choice print the result

Program ends

In [8]:
#Q33 Write a program that calculates the greatest common divisor (GCD) of two numbers using the Euclidean algorithm.


def gcd(a, b):
    if (a == 0):
        return b
    if (b == 0):
        return a
    if (a == b):
        return a
    if (a > b):
        return gcd(a-b, b)
    return gcd(a, b-a)
 
# Driver program to test above function
a = int(input("Enter the number :" ))
b = int(input("Enter the number :" ))
if(gcd(a, b)):
    print('GCD of', a, 'and', b, 'is', gcd(a, b))
else:
    print('not found')

Enter the number : 72
Enter the number : 48


GCD of 72 and 48 is 24


Let  a, b  be the two numbers

a mod b = R

Let  a = b  and  b = R

Repeat Steps 2 and 3 until  a mod b  is greater than 0

GCD = b

Finish

In [9]:
#Q34. Build a program that performs matrix multiplication using nested loops and conditional statements.


def matrix_multiplication(A, B):
    if len(A[0]) != len(B):
        raise ValueError("Matrices cannot be multiplied.")
    C = [[0 for _ in range(len(B[0]))] for _ in range(len(A))]
    for i in range(len(A)):
        
        for j in range(len(B[0])):
            
            for k in range(len(B)):
               
                C[i][j] += A[i][k] * B[k][j]

    return C



A = [[1, 2, 3], [4, 5, 6]]
B = [[7, 8], [9, 10], [11, 12]]

C = matrix_multiplication(A, B)

print(C)

[[58, 64], [139, 154]]


Store the matrix dimensions in different variables

Check if the matrices are multiplication compatible.

If no, terminate the program, otherwise continue.

Iterate over the rows of matrix A using an index-variable i

Inside the first loop, iterate over the columns of matrix B using the index-variable j

Now initialize a variable curr_val to 0

Create another loop iterating over the column dimension of A (or equivalently the row dimension of B) using a variable k

For each iteration of the innermost loop, add the value of A[i][k]×B[k][j] to the variable curr_val

After each iteration of the innermost loop, assign the value of curr_val to C[i][j]

In [28]:
#Q35. Create a program that simulates a basic text-based tic-tac-toe game against the computer.

import numpy as np
import random
from time import sleep
def create_board():
    return(np.array([[0, 0, 0],
                     [0, 0, 0],
                     [0, 0, 0]]))
def possibilities(board):
    l = []
 
    for i in range(len(board)):
        for j in range(len(board)):
 
            if board[i][j] == 0:
                l.append((i, j))
    return(l)
def random_place(board, player):
    selection = possibilities(board)
    current_loc = random.choice(selection)
    board[current_loc] = player
    return(board)
def row_win(board, player):
    for x in range(len(board)):
        win = True
 
        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                continue
 
        if win == True:
            return(win)
    return(win)
def col_win(board, player):
    for x in range(len(board)):
        win = True
 
        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                continue
 
        if win == True:
            return(win)
    return(win)
def diag_win(board, player):
    win = True
    y = 0
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
    if win:
        return win
    win = True
    if win:
        for x in range(len(board)):
            y = len(board) - 1 - x
            if board[x, y] != player:
                win = False
    return win
def evaluate(board):
    winner = 0
 
    for player in [1, 2]:
        if (row_win(board, player) or
                col_win(board, player) or
                diag_win(board, player)):
 
            winner = player
 
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner
def play_game():
    board, winner, counter = create_board(), 0, 1
    print(board)
    sleep(2)
 
    while winner == 0:
        for player in [1, 2]:
            board = random_place(board, player)
            print("Board after " + str(counter) + " move")
            print(board)
            sleep(2)
            counter += 1
            winner = evaluate(board)
            if winner != 0:
                break
    return(winner)
 
 

print("Winner is: " + str(play_game()))

[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 0]
 [0 1 0]]
Board after 2 move
[[0 0 0]
 [0 0 0]
 [2 1 0]]
Board after 3 move
[[0 0 0]
 [1 0 0]
 [2 1 0]]
Board after 4 move
[[0 0 0]
 [1 0 0]
 [2 1 2]]
Board after 5 move
[[0 0 0]
 [1 1 0]
 [2 1 2]]
Board after 6 move
[[0 0 0]
 [1 1 2]
 [2 1 2]]
Board after 7 move
[[0 1 0]
 [1 1 2]
 [2 1 2]]
Winner is: 1


The code starts by importing all the necessary libraries.

Next, it creates an empty board and checks for empty places on the board.

The possibilities() function then selects a random place for the player and returns the board.

The row_win(), col_win(), and diag_win() functions check whether the player has three of their marks in a horizontal row, vertical row, or diagonal row, respectively.

If so, they return True and win is set to that player.

If not, they continue checking until either one of these conditions is met.

Finally, evaluate() determines whether there is a winner or tie based on the results of the other two functions.

If there is no winner (i.e., all players have zero marks), then no action is taken and the program terminates with an error message stating that there was no game played!

Otherwise, if both players have at least one mark in each column and row but not in any diagonal line (a situation called a deadlock), then play continues as normal with whoever has more wins being declared the winner.

In case of a tie, play goes back to evaluating who won last time; this process repeats until somebody wins or somebody loses all their pieces (which ends up being Game Over

The code creates an empty board and then checks for the player having three marks in a horizontal row, vertical row or diagonal row.

If the player has achieved this, the code sets the winner variable to be equal to the corresponding value from that row on the board.

If there is no winner, then all of the players’ pieces are set to 0 and the program ends.

In [13]:
#Q36. Write a program that generates Fibonacci numbers up to a specified term using iterative methods

def PrintFibonacci(length):
    first = 0
    second = 1
    print(first, second, end=" ")
    length -= 2
    while length > 0:
        print(first + second, end=" ")
        temp = second
        second = first + second
        first = temp
        length -= 1

n=int(input("Enter the number :"))
print("Fibonacci Series - ")
PrintFibonacci(n)

Enter the number : 9


Fibonacci Series - 
0 1 1 2 3 5 8 13 21 

Create 2 variables and initialize them with 0 and 1 (first = 0, second = 1)

Create another variable to keep track of the length of the Fibonacci sequence to be printed (length) 

Loop (length is less than series length)Print first + second

Update first and second variable (first will point to the second, and the second will point to first + second)

Decrement the length variable and repeat from step 3

Once the loop terminates, terminate the program

In [16]:
#Q37. Develop a program that calculates the nth term of the Fibonacci sequence using memoization.

def fibMem(n, fibdict):
    if n in fibdict:
        return fibdict
    else:
        fibMem(n - 1, fibdict)
        fibdict[n] = fibdict[n - 1] + fibdict[n - 2]
        return fibdict
n=int(input("Enter the number :"))
print(fibMem(n, {0: 0, 1: 1}))

Enter the number : 9


{0: 0, 1: 1, 2: 1, 3: 2, 4: 3, 5: 5, 6: 8, 7: 13, 8: 21, 9: 34}


Like the alternative example for factorial memoization, the output is not the entire dictionary, but just fibMem2(8). Fair enough, if that’s all you need. And the complete dictionary is there - if you insert print(fibdict) right before the return statement you can have a peek. It’s just that you can’t get it out of the function - it gets discarded along with everything else once the final return of fibdict[n] occurs. In this way, it’s identical to how tri was behaving when we first tried to revise pascal().

In [23]:
#38. Create a program that generates a calendar for a given month and year using conditional statements.



mm = int(input("Enter the month  :"))
yy = int(input("Enter the year  :"))
  
month ={1:'January', 2:'February', 3:'March',  
        4:'April', 5:'May', 6:'June', 7:'July', 
        8:'August', 9:'September', 10:'October', 
        11:'November', 12:'December'} 
   

day =(yy-1)% 400
day = (day//100)*5 + ((day % 100) - (day % 100)//4) + ((day % 100)//4)*2
day = day % 7
  
nly =[31, 28, 31, 30, 31, 30,  
      31, 31, 30, 31, 30, 31] 
ly =[31, 29, 31, 30, 31, 30,  
     31, 31, 30, 31, 30, 31] 
s = 0
  
if yy % 4 == 0: 
    for i in range(mm-1): 
        s+= ly[i] 
else: 
    for i in range(mm-1): 
        s+= nly[i] 
  
day += s % 7
day = day % 7
space ='' 
space = space.rjust(2, ' ') 
print(month[mm], yy) 
print('Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa') 
  
if mm == 9 or mm == 4 or mm == 6 or mm == 11:  
    for i in range(31 + day): 
          
        if i<= day: 
            print(space, end =' ') 
        else: 
            print("{:02d}".format(i-day), end =' ') 
            if (i + 1)% 7 == 0: 
                print() 
elif mm == 2: 
    if yy % 4 == 0: 
        p = 30
    else: 
        p = 29
          
    for i in range(p + day): 
        if i<= day: 
            print(space, end =' ') 
        else: 
            print("{:02d}".format(i-day), end =' ') 
            if (i + 1)% 7 == 0: 
                print()  
else: 
    for i in range(32 + day): 
          
        if i<= day: 
            print(space, end =' ') 
        else: 
            print("{:02d}".format(i-day), end =' ') 
            if (i + 1)% 7 == 0: 
                print() 

Enter the month  : 11
Enter the year  : 2006


November 2006
Su Mo Tu We Th Fr Sa
         01 02 03 04 
05 06 07 08 09 10 11 
12 13 14 15 16 17 18 
19 20 21 22 23 24 25 
26 27 28 29 30 

In [27]:
#Q39. Build a program that simulates a basic text-based blackjack game against the computer.

import random 
  
card_categories = ['Hearts', 'Diamonds', 'Clubs', 'Spades'] 
cards_list = ['Ace', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Jack', 'Queen', 'King'] 
deck = [(card, category) for category in card_categories for card in cards_list] 
  
def card_value(card): 
    if card[0] in ['Jack', 'Queen', 'King']: 
        return 10
    elif card[0] == 'Ace': 
        return 11
    else: 
        return int(card[0]) 
  
random.shuffle(deck) 
player_card = [deck.pop(), deck.pop()] 
dealer_card = [deck.pop(), deck.pop()] 
  
while True: 
    player_score = sum(card_value(card) for card in player_card) 
    dealer_score = sum(card_value(card) for card in dealer_card) 
    print("Cards Player Has:", player_card) 
    print("Score Of The Player:", player_score) 
    print("\n") 
    choice = input('What do you want? ["play" to request another card, "stop" to stop]: ').lower() 
    if choice == "play": 
        new_card = deck.pop() 
        player_card.append(new_card) 
    elif choice == "stop": 
        break
    else: 
        print("Invalid choice. Please try again.") 
        continue
  
    if player_score > 21: 
        print("Cards Dealer Has:", dealer_card) 
        print("Score Of The Dealer:", dealer_score) 
        print("Cards Player Has:", player_card) 
        print("Score Of The Player:", player_score) 
        print("Dealer wins (Player Loss Because Player Score is exceeding 21)") 
        break
  
while dealer_score < 17: 
    new_card = deck.pop() 
    dealer_card.append(new_card) 
    dealer_score += card_value(new_card) 
  
print("Cards Dealer Has:", dealer_card) 
print("Score Of The Dealer:", dealer_score) 
print("\n") 
  
if dealer_score > 21: 
    print("Cards Dealer Has:", dealer_card) 
    print("Score Of The Dealer:", dealer_score) 
    print("Cards Player Has:", player_card) 
    print("Score Of The Player:", player_score) 
    print("Player wins (Dealer Loss Because Dealer Score is exceeding 21)") 
elif player_score > dealer_score: 
    print("Cards Dealer Has:", dealer_card) 
    print("Score Of The Dealer:", dealer_score) 
    print("Cards Player Has:", player_card) 
    print("Score Of The Player:", player_score) 
    print("Player wins (Player Has High Score than Dealer)") 
elif dealer_score > player_score: 
    print("Cards Dealer Has:", dealer_card) 
    print("Score Of The Dealer:", dealer_score) 
    print("Cards Player Has:", player_card) 
    print("Score Of The Player:", player_score) 
    print("Dealer wins (Dealer Has High Score than Player)") 
else: 
    print("Cards Dealer Has:", dealer_card) 
    print("Score Of The Dealer:", dealer_score) 
    print("Cards Player Has:", player_card) 
    print("Score Of The Player:", player_score) 
    print("It's a tie.")

Cards Player Has: [('7', 'Clubs'), ('King', 'Hearts')]
Score Of The Player: 17




What do you want? ["play" to request another card, "stop" to stop]:  stop


Cards Dealer Has: [('10', 'Diamonds'), ('2', 'Hearts'), ('7', 'Hearts')]
Score Of The Dealer: 19


Cards Dealer Has: [('10', 'Diamonds'), ('2', 'Hearts'), ('7', 'Hearts')]
Score Of The Dealer: 19
Cards Player Has: [('7', 'Clubs'), ('King', 'Hearts')]
Score Of The Player: 17
Dealer wins (Dealer Has High Score than Player)


Firstly we import the Python Random module in our code for shuffling.

After successfully importing the random module, we set up the deck by creating two lists: card_categories and cards_list.The deck is then constructed as a list of tuples, each representing a card 

In this step, we create a function called card_values() which takes cards as input and returns the corresponding point of the card. Cards numbered from 2 to 10 have the same points as their number. Face cards like Jack, Queen, and King have 10 points, and Aces have 11 points.

After creating the function, we will use the random.shuffle() method to shuffle the cards and also after using random.shuffle() method we will need to deal the initial card so that Two hands of cards are distributed: one for the player and one for the dealer. Each hand starts with two cards.

Next, with everything done, let’s write code that allows a player to “play”

After a player has completed his turn, it is the dealer’s turn to draw cards until he has at least 17 points.

This is the final step in which we have to determine the winner by comparing the player and dealer scores.

If the player has scored greater than 21 then the player loses the game and the dealer wins the game. 
If the dealer has a score greater than 21 then the dealer loses the game and the player wins the game. 
If the player has scored higher than the dealer then the player wins the game. 
If the dealer has scored higher than the player’s score then the dealer wins the game. 
If both player and dealer have the same score then the game is considered a tie.

In [26]:
#40. Write a program that generates the prime factors of a given number using trial division.



def TrialDivision(N):
    i = 2
    k = int(N ** 0.5)
    while(i<= k):
        if(N % i == 0):
            return 0
        i += 1
    return 1
     

N = int(input("Enter the input :"))
p = TrialDivision(N)
 
if(p):
    print("Prime")
else:
    print("Composite")

Enter the input : 77


Composite


The while loop is executed for a maximum of square root(N) times. Therefore, the time complexity of the while loop is O(sqrt(N)).

The running time of all the if conditions are constant. Therefore, the time complexity of the if statements are O(1).

Therefore, the overall time complexity is O(sqrt(N)).

Optimized Trial Division Method: The above trial division method can be further optimized by eliminating all even numbers in the range [2, K] where K = square root(N) as 2 is the only even prime number. 

The overall complexity still remains the same but the number of executions gets reduced by half.